--- #YAML:1.0
name:                JavaScript
version:             1.10
abstract:            Perl extension for executing embedded JavaScript
license:             perl
author:              
    - Claes Jakobsson <claesjac@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::Exception:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3

resources:
    repository: svn://svn.versed.se/public/Perl/modules/JavaScript
