# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         JavaScript
version:      1.00_01
version_from: lib/JavaScript.pm
installdirs:  site
requires:
    Test::Exception:               0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
