#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         JavaScript
version:      0.53
version_from: JavaScript.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
