--- #YAML:1.0
name:                JavaScript
version:             1.03
abstract:            Perl extension for executing embedded JavaScript
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Test::Exception:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Claes Jakobsson <claesjac@cpan.org>
